# Generated by Django 4.2.9 on 2024-12-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('salary_expectation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stage', models.CharField(choices=[('Lead', 'Lead'), ('Training Completed', 'Training Completed'), ('Background Check', 'Background Check'), ('Unassigned Caregiver', 'Unassigned'), ('Active Caregiver', 'Active')], default='Lead', max_length=50)),
            ],
        ),
    ]
