# Generated by Django 4.2.9 on 2024-12-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='stage',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Interview Completed', 'Interview Completed'), ('Training Completed', 'Training Completed'), ('Background Checked', 'Background Checked'), ('Ready to Work', 'Ready to Work')], default='Lead', max_length=50),
        ),
        migrations.CreateModel(
            name='CaregiverNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='caregiver_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recruitment.caregiver')),
            ],
        ),
    ]
