# Generated by Django 4.2.9 on 2025-01-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_caregiver_stage_caregivernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='country_of_origin',
            field=models.CharField(default='Romania', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='current_location',
            field=models.CharField(default='Romania', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='house_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='location_preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='mental_health_acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='professional_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
