# Generated by Django 4.2.9 on 2024-12-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Consultation Scheduled', 'Consultation Scheduled'), ('Under Consideration', 'Under Consideration'), ('Caregiver Interview Scheduled', 'Caregiver Interview Scheduled'), ('Caregiver Consideration', 'Caregiver Consideration'), ('Ready for Service', 'Ready for Service')], default='Prospecting', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
