# Generated by Django 4.2.9 on 2024-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0004_lead_location_alter_lead_phone_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consultation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Consultation Scheduled', 'Consultation Scheduled'), ('Under Consideration', 'Under Consideration'), ('Caregiver Interview Scheduled', 'Caregiver Interview Scheduled'), ('Caregiver Consideration', 'Caregiver Consideration'), ('Ready for Service', 'Ready for Service')], default='Prospecting', max_length=50),
        ),
    ]
