# Generated by Django 4.2.9 on 2024-12-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0005_lead_consultation_datetime_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='medical_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='relation',
            field=models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('friend', 'Friend'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='services_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
