# Generated by Django 4.2.9 on 2024-12-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0006_lead_age_lead_medical_summary_lead_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
