# Generated by Django 4.2.9 on 2025-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0010_lead_consultation_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='caregiver_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='days_per_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='hours_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Consultation Scheduled', 'Consultation Scheduled'), ('Under Consideration', 'Under Consideration'), ('Caregiver Interview Scheduled', 'Caregiver Interview Scheduled'), ('Caregiver Consideration', 'Caregiver Consideration'), ('Ready for Service', 'Ready for Service'), ('Active Client', 'Active Client')], default='Prospecting', max_length=50),
        ),
    ]
