# Generated by Django 4.2.9 on 2025-01-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_caregiver_stage_caregivernotes'),
        ('sales_pipeline', '0011_lead_additional_details_lead_caregiver_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='recruitment.caregiver'),
        ),
    ]
