# Generated by Django 4.2.9 on 2025-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0013_alter_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Consultation Scheduled', 'Consultation Scheduled'), ('Under Consideration', 'Under Consideration'), ('Caregiver Interview Scheduled', 'Caregiver Interview Scheduled'), ('Caregiver Consideration', 'Caregiver Consideration'), ('Active Client', 'Active Client')], default='Prospecting', max_length=50),
        ),
    ]
